from __future__ import annotations

from app.agents.context_manager import ContextManager
from app.agents.memory_manager import MemoryManager
from app.agents.prompt_assembler import PromptAssembler
from app.clients.asr_client import ASRClient
from app.clients.llm_client import LLMClient
from app.clients.pronunciation_client import PronunciationClient
from app.clients.tts_client import TTSClient
from app.repositories.profile_repository import ProfileRepository
from app.schemas.agent import DailyPlanRequest, SpeakingChatRequest, TutorChatRequest, WritingCorrectRequest


class AgentService:
    """Implements the mandated AI chain: memory -> prompt -> context -> LLM -> persistence."""

    def __init__(
        self,
        memory_manager: MemoryManager,
        prompt_assembler: PromptAssembler,
        context_manager: ContextManager,
        llm_client: LLMClient,
        repository: ProfileRepository,
    ) -> None:
        self.memory_manager = memory_manager
        self.prompt_assembler = prompt_assembler
        self.context_manager = context_manager
        self.llm_client = llm_client
        self.repository = repository
        self.asr_client = ASRClient()
        self.tts_client = TTSClient()
        self.pronunciation_client = PronunciationClient()

    def tutor_chat(self, request: TutorChatRequest) -> dict:
        memory = self.memory_manager.load_user_memory(request.user_id)
        context = self.context_manager.load_context(request.user_id, request.session_id, request.scene)
        messages = self.prompt_assembler.build_messages(
            scene=request.scene,
            user_memory=memory,
            context=context,
            user_input=request.message,
        )

        reply = self.llm_client.chat(messages)

        self.context_manager.append_turn(request.user_id, request.session_id, request.scene, "user", request.message)
        self.context_manager.append_turn(request.user_id, request.session_id, request.scene, "assistant", reply)

        persisted = self._persist_learning_artifacts(request, reply)
        return {"reply": reply, "scene": request.scene, "persisted": persisted}

    def clear_context(self, user_id: int, session_id: str, scene: str) -> None:
        self.context_manager.clear(user_id, session_id, scene)

    def generate_daily_plan(self, request: DailyPlanRequest) -> dict:
        memory = self.memory_manager.load_user_memory(request.user_id)
        context = self.context_manager.load_context(request.user_id, request.session_id, "daily_plan")
        user_input = (
            f"请为 {request.task_date} 生成每日学习计划。"
            f"用户今日可用学习时长：{request.available_minutes} 分钟。"
            "请覆盖旧知识复习、新知识学习、口语或写作输出练习、短板专项训练。"
        )
        messages = self.prompt_assembler.build_messages(
            scene="daily_plan",
            user_memory=memory,
            context=context,
            user_input=user_input,
        )
        ai_summary = self.llm_client.chat(messages)
        tasks = self._build_structured_daily_tasks(memory, request.available_minutes, ai_summary)
        self.repository.replace_daily_tasks(request.user_id, request.task_date, tasks)
        self.context_manager.append_turn(request.user_id, request.session_id, "daily_plan", "user", user_input)
        self.context_manager.append_turn(request.user_id, request.session_id, "daily_plan", "assistant", ai_summary)
        return {"taskDate": request.task_date, "summary": ai_summary, "tasks": tasks}

    def correct_writing(self, request: WritingCorrectRequest) -> dict:
        memory = self.memory_manager.load_user_memory(request.user_id)
        context = self.context_manager.load_context(request.user_id, request.session_id, "writing")
        user_input = (
            f"作文标题：{request.title}\n\n"
            f"用户作文：\n{request.content}\n\n"
            "请按四层批改逻辑输出：基础错误、中式英语优化、句式词汇升级、逻辑结构优化、优化范文、避坑要点。"
        )
        messages = self.prompt_assembler.build_messages(
            scene="writing",
            user_memory=memory,
            context=context,
            user_input=user_input,
        )
        llm_feedback = self.llm_client.chat(messages)
        result = self._build_structured_writing_result(request.content, llm_feedback)

        self.repository.save_error_record(
            user_id=request.user_id,
            source_type="writing",
            original_content=request.content,
            corrected_content=result["correctedContent"],
            error_type="writing_correction",
            explanation="Writing correction generated by EasiTalk AI Agent.",
            knowledge_points=result["knowledgePoints"],
        )
        self.context_manager.append_turn(request.user_id, request.session_id, "writing", "user", user_input)
        self.context_manager.append_turn(request.user_id, request.session_id, "writing", "assistant", llm_feedback)
        return result

    def speaking_chat(self, request: SpeakingChatRequest) -> dict:
        asr = self.asr_client.transcribe(request.audio_url, request.message)
        transcript = asr["text"] or request.message
        tutor_request = TutorChatRequest(
            user_id=request.user_id,
            session_id=request.session_id,
            scene="speaking",
            message=transcript,
        )
        chat_result = self.tutor_chat(tutor_request)
        pronunciation = self.pronunciation_client.evaluate(transcript)
        tts = self.tts_client.synthesize(chat_result["reply"])
        return {
            "transcript": transcript,
            "reply": chat_result["reply"],
            "pronunciation": pronunciation,
            "ttsText": tts["text"],
            "ttsAudioUrl": tts["audioUrl"],
            "asr": asr,
            "persisted": chat_result["persisted"],
        }

    def _persist_learning_artifacts(self, request: TutorChatRequest, reply: str) -> dict[str, int | bool]:
        """Minimal deterministic parser. Later replace with model JSON schema extraction."""
        saved_errors = 0
        saved_words = 0

        if request.scene in {"writing", "speaking"} and len(request.message.strip()) > 0:
            self.repository.save_error_record(
                user_id=request.user_id,
                source_type=request.scene,
                original_content=request.message,
                corrected_content=reply[:1000],
                error_type="ai_feedback",
                explanation="AI Agent generated adaptive feedback for this output.",
                knowledge_points=[request.scene],
            )
            saved_errors = 1

        # Simple vocabulary extraction marker: user can send "word:xxx=meaning" in early dev.
        if request.message.lower().startswith("word:") and "=" in request.message:
            raw = request.message[5:]
            word, meaning = raw.split("=", 1)
            self.repository.save_word(request.user_id, word.strip(), meaning.strip())
            saved_words = 1

        return {"errorRecords": saved_errors, "words": saved_words, "contextSaved": True}

    @staticmethod
    def _build_structured_daily_tasks(memory: dict, available_minutes: int, ai_summary: str) -> list[dict]:
        """Build a dynamic four-skill curriculum from the user's level and weaknesses.

        The plan is deterministic and schema-stable so Go/Web can render it reliably;
        the LLM summary is used as the teaching rationale while task allocation is kept
        auditable and safe for production.
        """
        level = str(memory.get("cefr_level") or "A1").upper()
        goal = memory.get("learning_goal") or "综合英语提升"
        weak_grammar = AgentService._join(memory.get("weak_grammar_points"), "基础时态与句型")
        speaking_weaknesses = AgentService._join(memory.get("speaking_weaknesses"), "发音、停顿与表达自然度")
        writing_weaknesses = AgentService._join(memory.get("writing_weaknesses"), "句式丰富度与逻辑衔接")
        error_words = AgentService._join(memory.get("error_prone_words"), "近期错词与生词")

        skill_weights = AgentService._skill_weights(goal, memory)
        minutes = AgentService._allocate_minutes(available_minutes, skill_weights)
        difficulty = AgentService._difficulty_for_level(level)
        language_policy = "中英双语讲解" if level in {"A1", "A2"} else "英文优先，复杂点中文补充"

        tasks = [
            {
                "taskType": "review",
                "skill": "review",
                "module": "语境化复习",
                "title": f"复习：{error_words}",
                "estimatedMinutes": minutes["review"],
                "difficulty": difficulty,
                "level": level,
                "languagePolicy": language_policy,
                "learningValue": "先巩固个人错词、错句和已暴露薄弱点，避免今天的新输入建立在旧错误上。",
                "instructions": "用原句语境复习 3-5 个生词/错句：先遮住释义回忆，再朗读原句，最后写出一个新例句。",
                "outputRequirement": "提交至少 1 个新造句或口头复述。",
                "successCriteria": ["能说出词义", "能在新句子中正确使用", "同类错误不重复出现"],
                "adjustmentSignal": "若回忆失败超过 40%，明日增加复习占比并降低新内容难度。",
                "aiSummary": ai_summary[:500],
            },
            {
                "taskType": "listening",
                "skill": "listening",
                "module": "听力输入",
                "title": f"听力：{goal} 场景盲听 + 精听",
                "estimatedMinutes": minutes["listening"],
                "difficulty": difficulty,
                "level": level,
                "languagePolicy": language_policy,
                "learningValue": "听力是后续口语输出的输入来源，先建立声音、词义和句意的连接。",
                "instructions": f"选择 {AgentService._scene_for_goal(goal)} 的短材料：先不看文本听 1 遍，再逐句精听并记录没听出的关键词。",
                "outputRequirement": "写下 3 个听到的关键词，并标记最难的一句。",
                "successCriteria": ["能抓住主旨", "能复述关键词", "能定位 1 个难句"],
                "adjustmentSignal": "若主旨听不出，明日材料降一级；若能完整复述，明日增加语速或长度。",
            },
            {
                "taskType": "reading",
                "skill": "reading",
                "module": "阅读透镜",
                "title": f"阅读：围绕 {weak_grammar} 的短文理解",
                "estimatedMinutes": minutes["reading"],
                "difficulty": difficulty,
                "level": level,
                "languagePolicy": language_policy,
                "learningValue": "阅读负责补充可理解输入，并把薄弱语法放回真实语境中理解。",
                "instructions": f"阅读一段 {AgentService._reading_length(level)} 的材料，使用阅读透镜提取低曝光生词，重点观察：{weak_grammar}。",
                "outputRequirement": "收藏 2 个有价值表达，并用自己的话写 1 句中文主旨。",
                "successCriteria": ["理解主旨", "识别目标语法", "至少沉淀 1 个可复用表达"],
                "adjustmentSignal": "若生词过多，明日降低文本难度；若生词很少，明日提高材料长度。",
            },
            {
                "taskType": "speaking",
                "skill": "speaking",
                "module": "口语输出",
                "title": f"口语：{AgentService._scene_for_goal(goal)} 三轮表达",
                "estimatedMinutes": minutes["speaking"],
                "difficulty": difficulty,
                "level": level,
                "languagePolicy": language_policy,
                "learningValue": "通过主动说暴露真实卡点，让 AI 把发音、语序和中式表达沉淀进学习档案。",
                "instructions": f"围绕今日听读材料进行 3 轮口语回答，每轮只说 1-2 句，重点修正：{speaking_weaknesses}。",
                "outputRequirement": "完成至少 1 次录音或文本口语提交。",
                "successCriteria": ["能完成回答", "停顿减少", "至少修正 1 个表达"],
                "adjustmentSignal": "若表达卡顿严重，明日增加句型支架；若表达流畅，明日增加追问轮次。",
            },
            {
                "taskType": "writing",
                "skill": "writing",
                "module": "写作输出",
                "title": f"写作：{goal} 迷你输出",
                "estimatedMinutes": minutes["writing"],
                "difficulty": difficulty,
                "level": level,
                "languagePolicy": language_policy,
                "learningValue": "写作把输入内容转化为可检查的结构化输出，便于 AI 精准定位语法和逻辑短板。",
                "instructions": f"写 {AgentService._writing_length(level)}，主题沿用今日听读材料，重点检查：{writing_weaknesses}。",
                "outputRequirement": "提交短文给 AI 批改，并把 1 个高频错误加入错题库。",
                "successCriteria": ["主题明确", "句子基本正确", "至少完成 1 处表达升级"],
                "adjustmentSignal": "若错误集中在同类语法，明日安排专项 drill；若结构清晰，明日增加连接词与复杂句。",
            },
        ]
        return [task for task in tasks if task["estimatedMinutes"] > 0]

    @staticmethod
    def _skill_weights(goal: str, memory: dict) -> dict[str, float]:
        weights = {"review": 0.18, "listening": 0.20, "reading": 0.20, "speaking": 0.22, "writing": 0.20}
        goal_text = goal.lower()
        if any(keyword in goal_text for keyword in ["口语", "speaking", "travel", "conversation"]):
            weights["speaking"] += 0.10
            weights["listening"] += 0.05
            weights["writing"] -= 0.08
            weights["reading"] -= 0.07
        if any(keyword in goal_text for keyword in ["写作", "writing", "ielts", "雅思", "考试"]):
            weights["writing"] += 0.10
            weights["reading"] += 0.05
            weights["speaking"] -= 0.05
            weights["listening"] -= 0.05
        if memory.get("speaking_weaknesses"):
            weights["speaking"] += 0.04
        if memory.get("writing_weaknesses"):
            weights["writing"] += 0.04
        if memory.get("error_prone_words"):
            weights["review"] += 0.04
        total = sum(max(value, 0.05) for value in weights.values())
        return {key: max(value, 0.05) / total for key, value in weights.items()}

    @staticmethod
    def _allocate_minutes(available_minutes: int, weights: dict[str, float]) -> dict[str, int]:
        if available_minutes < 25:
            active = ["review", "listening", "speaking"]
        elif available_minutes < 40:
            active = ["review", "listening", "reading", "speaking"]
        else:
            active = ["review", "listening", "reading", "speaking", "writing"]
        total_weight = sum(weights[key] for key in active)
        minutes = {key: 0 for key in weights}
        remaining = available_minutes
        for index, key in enumerate(active):
            if index == len(active) - 1:
                minutes[key] = max(5, remaining)
            else:
                value = max(5, round(available_minutes * weights[key] / total_weight))
                minutes[key] = value
                remaining -= value
        return minutes

    @staticmethod
    def _difficulty_for_level(level: str) -> str:
        return {
            "A1": "i+1：短句、慢速、强支架",
            "A2": "i+1：日常场景、基础复合句",
            "B1": "i+1：真实场景、适度追问",
            "B2": "i+1：观点表达、复杂句与地道替换",
            "C1": "高阶表达、语域和论证质量",
        }.get(level, "i+1：略高于当前水平")

    @staticmethod
    def _scene_for_goal(goal: str) -> str:
        if "商务" in goal:
            return "商务会议/邮件沟通"
        if "雅思" in goal or "考试" in goal:
            return "考试口语/写作话题"
        if "旅行" in goal:
            return "旅行问路、入住和点餐"
        return "日常生活交流"

    @staticmethod
    def _reading_length(level: str) -> str:
        return "80-120 词" if level in {"A1", "A2"} else "150-220 词"

    @staticmethod
    def _writing_length(level: str) -> str:
        return "3-5 句" if level in {"A1", "A2"} else "80-120 词"

    @staticmethod
    def _join(values: object, fallback: str) -> str:
        if isinstance(values, list) and values:
            return "、".join(str(item) for item in values if str(item).strip()) or fallback
        if isinstance(values, str) and values.strip():
            return values
        return fallback

    @staticmethod
    def _build_structured_writing_result(original: str, llm_feedback: str) -> dict:
        corrected = original.strip()
        replacements = {
            "I yesterday go": "I went yesterday",
            "I go to": "I went to",
            "more better": "better",
            "very like": "really like",
        }
        issues: list[dict] = []
        for wrong, right in replacements.items():
            if wrong.lower() in corrected.lower():
                corrected = corrected.replace(wrong, right)
                issues.append(
                    {
                        "type": "grammar",
                        "original": wrong,
                        "suggestion": right,
                        "explanation": "该表达不符合自然英语或语法规则，建议替换为更地道表达。",
                    }
                )

        if not issues:
            issues.append(
                {
                    "type": "style",
                    "original": "整体表达",
                    "suggestion": "增加连接词、具体例子和更自然的句式。",
                    "explanation": "当前文本可读，但还可以通过逻辑衔接和句式变化提升质量。",
                }
            )

        return {
            "correctedContent": corrected,
            "bandScore": 5.5 if len(original.split()) < 80 else 6.0,
            "issues": issues,
            "upgradedExpressions": [
                {"from": "I think", "to": "From my perspective"},
                {"from": "good", "to": "beneficial / effective"},
            ],
            "modelEssay": corrected + "\n\nIn addition, I will try to explain my ideas with clearer reasons and examples.",
            "knowledgePoints": ["grammar", "word_choice", "coherence"],
            "summary": llm_feedback,
        }

