from app.agents.context_manager import ContextManager
from app.agents.memory_manager import MemoryManager
from app.agents.prompt_assembler import PromptAssembler
from app.clients.asr_client import ASRClient
from app.clients.llm_client import LLMClient
from app.clients.pronunciation_client import PronunciationClient
from app.clients.tts_client import TTSClient
from app.repositories.profile_repository import ProfileRepository
from app.schemas.agent import DailyPlanRequest, SpeakingChatRequest, TutorChatRequest, WritingCorrectRequest


class AgentService:
    """Implements the mandated AI chain: memory -> prompt -> context -> LLM -> persistence."""

    def __init__(
        self,
        memory_manager: MemoryManager,
        prompt_assembler: PromptAssembler,
        context_manager: ContextManager,
        llm_client: LLMClient,
        repository: ProfileRepository,
    ) -> None:
        self.memory_manager = memory_manager
        self.prompt_assembler = prompt_assembler
        self.context_manager = context_manager
        self.llm_client = llm_client
        self.repository = repository
        self.asr_client = ASRClient()
        self.tts_client = TTSClient()
        self.pronunciation_client = PronunciationClient()

    def tutor_chat(self, request: TutorChatRequest) -> dict:
        memory = self.memory_manager.load_user_memory(request.user_id)
        context = self.context_manager.load_context(request.user_id, request.session_id, request.scene)
        messages = self.prompt_assembler.build_messages(
            scene=request.scene,
            user_memory=memory,
            context=context,
            user_input=request.message,
        )

        reply = self.llm_client.chat(messages)

        self.context_manager.append_turn(request.user_id, request.session_id, request.scene, "user", request.message)
        self.context_manager.append_turn(request.user_id, request.session_id, request.scene, "assistant", reply)

        persisted = self._persist_learning_artifacts(request, reply)
        return {"reply": reply, "scene": request.scene, "persisted": persisted}

    def clear_context(self, user_id: int, session_id: str, scene: str) -> None:
        self.context_manager.clear(user_id, session_id, scene)

    def generate_daily_plan(self, request: DailyPlanRequest) -> dict:
        memory = self.memory_manager.load_user_memory(request.user_id)
        context = self.context_manager.load_context(request.user_id, request.session_id, "daily_plan")
        user_input = (
            f"请为 {request.task_date} 生成每日学习计划。"
            f"用户今日可用学习时长：{request.available_minutes} 分钟。"
            "请覆盖旧知识复习、新知识学习、口语或写作输出练习、短板专项训练。"
        )
        messages = self.prompt_assembler.build_messages(
            scene="daily_plan",
            user_memory=memory,
            context=context,
            user_input=user_input,
        )
        ai_summary = self.llm_client.chat(messages)
        tasks = self._build_structured_daily_tasks(memory, request.available_minutes, ai_summary)
        self.repository.replace_daily_tasks(request.user_id, request.task_date, tasks)
        self.context_manager.append_turn(request.user_id, request.session_id, "daily_plan", "user", user_input)
        self.context_manager.append_turn(request.user_id, request.session_id, "daily_plan", "assistant", ai_summary)
        return {"taskDate": request.task_date, "summary": ai_summary, "tasks": tasks}

    def correct_writing(self, request: WritingCorrectRequest) -> dict:
        memory = self.memory_manager.load_user_memory(request.user_id)
        context = self.context_manager.load_context(request.user_id, request.session_id, "writing")
        user_input = (
            f"作文标题：{request.title}\n\n"
            f"用户作文：\n{request.content}\n\n"
            "请按四层批改逻辑输出：基础错误、中式英语优化、句式词汇升级、逻辑结构优化、优化范文、避坑要点。"
        )
        messages = self.prompt_assembler.build_messages(
            scene="writing",
            user_memory=memory,
            context=context,
            user_input=user_input,
        )
        llm_feedback = self.llm_client.chat(messages)
        result = self._build_structured_writing_result(request.content, llm_feedback)

        self.repository.save_error_record(
            user_id=request.user_id,
            source_type="writing",
            original_content=request.content,
            corrected_content=result["correctedContent"],
            error_type="writing_correction",
            explanation="Writing correction generated by EasiTalk AI Agent.",
            knowledge_points=result["knowledgePoints"],
        )
        self.context_manager.append_turn(request.user_id, request.session_id, "writing", "user", user_input)
        self.context_manager.append_turn(request.user_id, request.session_id, "writing", "assistant", llm_feedback)
        return result

    def speaking_chat(self, request: SpeakingChatRequest) -> dict:
        asr = self.asr_client.transcribe(request.audio_url, request.message)
        transcript = asr["text"] or request.message
        tutor_request = TutorChatRequest(
            user_id=request.user_id,
            session_id=request.session_id,
            scene="speaking",
            message=transcript,
        )
        chat_result = self.tutor_chat(tutor_request)
        pronunciation = self.pronunciation_client.evaluate(transcript)
        tts = self.tts_client.synthesize(chat_result["reply"])
        return {
            "transcript": transcript,
            "reply": chat_result["reply"],
            "pronunciation": pronunciation,
            "ttsText": tts["text"],
            "ttsAudioUrl": tts["audioUrl"],
            "asr": asr,
            "persisted": chat_result["persisted"],
        }

    def _persist_learning_artifacts(self, request: TutorChatRequest, reply: str) -> dict[str, int | bool]:
        """Minimal deterministic parser. Later replace with model JSON schema extraction."""
        saved_errors = 0
        saved_words = 0

        if request.scene in {"writing", "speaking"} and len(request.message.strip()) > 0:
            self.repository.save_error_record(
                user_id=request.user_id,
                source_type=request.scene,
                original_content=request.message,
                corrected_content=reply[:1000],
                error_type="ai_feedback",
                explanation="AI Agent generated adaptive feedback for this output.",
                knowledge_points=[request.scene],
            )
            saved_errors = 1

        # Simple vocabulary extraction marker: user can send "word:xxx=meaning" in early dev.
        if request.message.lower().startswith("word:") and "=" in request.message:
            raw = request.message[5:]
            word, meaning = raw.split("=", 1)
            self.repository.save_word(request.user_id, word.strip(), meaning.strip())
            saved_words = 1

        return {"errorRecords": saved_errors, "words": saved_words, "contextSaved": True}

    @staticmethod
    def _build_structured_daily_tasks(memory: dict, available_minutes: int, ai_summary: str) -> list[dict]:
        review_minutes = max(5, round(available_minutes * 0.25))
        input_minutes = max(5, round(available_minutes * 0.30))
        output_minutes = max(5, round(available_minutes * 0.30))
        weakness_minutes = max(5, available_minutes - review_minutes - input_minutes - output_minutes)

        weak_grammar = ", ".join(memory.get("weak_grammar_points") or []) or "高频薄弱语法"
        speaking_weaknesses = ", ".join(memory.get("speaking_weaknesses") or []) or "口语表达自然度"
        writing_weaknesses = ", ".join(memory.get("writing_weaknesses") or []) or "句式升级"

        return [
            {
                "taskType": "review",
                "title": "旧知识复习：生词与错题回顾",
                "estimatedMinutes": review_minutes,
                "learningValue": "巩固遗忘曲线中的高风险内容，降低重复错误。",
                "instructions": "复习最近易错生词、错句，并完成 3 道快速回忆题。",
                "aiSummary": ai_summary[:500],
            },
            {
                "taskType": "new_input",
                "title": f"新知识学习：{weak_grammar}",
                "estimatedMinutes": input_minutes,
                "learningValue": "围绕当前薄弱语法补齐输入，控制在用户可理解难度内。",
                "instructions": "阅读 1 组正误对比例句，并完成替换练习。",
            },
            {
                "taskType": "output",
                "title": "输出练习：场景口语或短写作",
                "estimatedMinutes": output_minutes,
                "learningValue": "通过主动输出暴露真实短板，形成 AI 复盘数据。",
                "instructions": f"围绕学习目标进行 3 轮输出，重点关注：{speaking_weaknesses}。",
            },
            {
                "taskType": "weakness_drill",
                "title": "短板专项：表达优化与复盘",
                "estimatedMinutes": weakness_minutes,
                "learningValue": "针对近期高频问题进行专项强化。",
                "instructions": f"完成针对性改写与复盘，写作重点关注：{writing_weaknesses}。",
            },
        ]

    @staticmethod
    def _build_structured_writing_result(original: str, llm_feedback: str) -> dict:
        corrected = original.strip()
        replacements = {
            "I yesterday go": "I went yesterday",
            "I go to": "I went to",
            "more better": "better",
            "very like": "really like",
        }
        issues: list[dict] = []
        for wrong, right in replacements.items():
            if wrong.lower() in corrected.lower():
                corrected = corrected.replace(wrong, right)
                issues.append(
                    {
                        "type": "grammar",
                        "original": wrong,
                        "suggestion": right,
                        "explanation": "该表达不符合自然英语或语法规则，建议替换为更地道表达。",
                    }
                )

        if not issues:
            issues.append(
                {
                    "type": "style",
                    "original": "整体表达",
                    "suggestion": "增加连接词、具体例子和更自然的句式。",
                    "explanation": "当前文本可读，但还可以通过逻辑衔接和句式变化提升质量。",
                }
            )

        return {
            "correctedContent": corrected,
            "bandScore": 5.5 if len(original.split()) < 80 else 6.0,
            "issues": issues,
            "upgradedExpressions": [
                {"from": "I think", "to": "From my perspective"},
                {"from": "good", "to": "beneficial / effective"},
            ],
            "modelEssay": corrected + "\n\nIn addition, I will try to explain my ideas with clearer reasons and examples.",
            "knowledgePoints": ["grammar", "word_choice", "coherence"],
            "summary": llm_feedback,
        }

