FROM golang:1.22-alpine AS dev

WORKDIR /app
ENV GOPROXY=https://goproxy.cn,direct
ENV GOSUMDB=off
RUN apk add --no-cache git

COPY go.mod ./
RUN go mod download

COPY . .
EXPOSE 3001
CMD ["go", "run", "./cmd/api"]

